phx_reference/web/router.ex
defmodule VanillaPhx.Router do
  use VanillaPhx.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VanillaPhx do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController, only: [:index, :edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", VanillaPhx do
  #   pipe_through :api
  # end
end

phx_reference/web/models/posts.ex
defmodule VanillaPhx.Posts do
  use VanillaPhx.Web, :model

  schema "posts" do
    field :title, :string
    field :body, :string
    field :created_at, Ecto.DateTime
    field :updated_at, Ecto.DateTime
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

phx_reference/web/controllers/page_controller.ex
defmodule VanillaPhx.PageController do
  use VanillaPhx.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

phx_reference/web/controllers/post_controller.ex
defmodule VanillaPhx.PostController do
  use VanillaPhx.Web, :controller
  alias VanillaPhx.Repo
  alias VanillaPhx.Posts

  def index(conn, _params) do
    render conn, "index.html"
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get(Posts, id)
    changeset = Posts.changeset(post)
    render conn, "edit.html", post: post, changeset: changeset
  end

  def update(conn, %{"id" => id, "posts" => %{"title" => title, "body" => body}}) do
  	post = Repo.get(Posts, id)
  	changeset = Posts.changeset(post, %{title: title, body: body})
  	Repo.update(changeset)
  	conn
  	|> put_layout(false)
    |> render("index.html")
  end
end

phx_reference/web/views/error_view.ex
defmodule VanillaPhx.ErrorView do
  use VanillaPhx.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

phx_reference/web/views/layout_view.ex
defmodule VanillaPhx.LayoutView do
  use VanillaPhx.Web, :view
end

phx_reference/web/views/page_view.ex
defmodule VanillaPhx.PageView do
  use VanillaPhx.Web, :view
end

phx_reference/web/views/post_view.ex
defmodule VanillaPhx.PostView do
  use VanillaPhx.Web, :view
end

phx_reference/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello VanillaPhx!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

phx_reference/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

phx_reference/web/templates/post/edit.html.eex
<h1>Edit Post</h1>

<%= form_for @changeset, post_path(@conn, :update, @post.id), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= textarea f, :body, placeholder: "Body", class: "form-control" %>
  </div>
  <%= submit "Save Post", class: "btn btn-primary" %>
<% end %>

phx_reference/web/templates/post/index.html.eex
Post Updated! <a href='/index.php'>Return</a>